version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - pytorch

conda:
  environment: environment.doc.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false
