name: env_qolmat
channels:
  - conda-forge
  - defaults
dependencies:
  - bump2version
  - flake8
  - ipykernel
  - jupyter
  - mypy
  - numpy=1.22
  - numpydoc
  - pandas
  - pytest
  - pytest-cov
  - python==3.8
  - scikit-learn
  - sphinx
  - sphinx-gallery
  - sphinx_rtd_theme
  - twine
  - wheel
  - jupyterlab
#   - fbprophet
  - s3fs
  - scikit-optimize
  - pyarrow
  - matplotlib
  - plotly
  - pip
  - pip:
    - -e .