name: env_qolmat
channels:
      - conda-forge
      - defaults
dependencies:
      - bump2version
      - ipykernel
      - jupyter
      - seaborn
      - sphinx
      - sphinx-gallery
      - sphinx_rtd_theme
      - twine
      - wheel
      - jupyterlab
      - s3fs
      - pyarrow
      - pip
      - pip:
              - -e .
              - flake8==6.0.0
              - matplotlib==3.6.2
              - numpy==1.24.1
              - numpydoc==1.5.0
              - mypy=0.911
              - pandas==1.5.2
              - plotly==5.11.0
              - pre-commit==2.21.0
              - pytest==7.2.0
              - pytest-cov==4.0.0
              - seaborn==0.12.2
              - scikit-learn==1.1.3
              - scikit-optimize==0.9.0
              - jupytext
              - missingpy
      - forge:
              - gcc=12.1.0
