name: env_qolmat_dev
channels:
    - conda-forge
    - defaults
dependencies:
    - bump2version=1.0.1
    - dcor=0.6
    - ipykernel=6.21.0
    - jupyter=1.0.0
    - jupyterlab=1.2.6
    - jupytext=1.14.4
    - hyperopt=0.2.7
    - numpy=1.24.4
    - packaging=23.1
    - pandas=2.0.1
    - python=3.8
    - pip=23.0.1
    - scipy=1.10.1
    - scikit-learn=1.2.2
    - sphinx=4.3.2
    - sphinx-gallery=0.10.1
    - sphinx_rtd_theme=1.0.0
    - statsmodels=0.14.0
    - twine=3.7.1
    - wheel=0.37.1
    - pip:
          - flake8==6.0.0
          - jupytext==1.14.4
          - matplotlib==3.6.2
          - plotly
          - mypy==1.1.1
          - numpydoc==1.5.0
          - pre-commit==2.21.0
          - pytest==7.2.0
          - pytest-cov==4.0.0
          - pytest-mock==3.10.0
          - sphinx_markdown_tables==0.0.17
          - -e .
