name: env_qolmat_ci
channels:
    - conda-forge
    - defaults
dependencies:
    - pip=23.0.1
    - pip:
          - codecov
          - flake8
          - matplotlib
          - mypy
          - numpy==1.19
          - numpydoc
          - pytest
          - pytest-cov
          - pytest-mock
          - tensorflow
          - -e .
