name: env_qolmat_ci
channels:
    - defaults
    - conda-forge
dependencies:
    - codecov
    - flake8
    - matplotlib
    - mypy
    - numpy
    - numpydoc
    - pytest
    - pytest-cov
    - pytest-mock
    - pip:
        - torch
        - -e .
