name: env_qolmat_ci
channels:
    - conda-forge
    - defaults
dependencies:
    - pip=23.0.1
    - pip:
          - codecov
          - flake8
          - matplotlib
          - mypy
          - numpy
          - numpydoc
          - pytest
          - pytest-cov
          - pytest-mock
          - torch==2.0.1
          - -e .
