name: env_qolmat_dev
channels:
    - conda-forge
    - defaults
dependencies:
      - bump2version=1.0.1
      - flake8=6.0.0
      - ipykernel=5.1.4
      - jupyter=1.0.0
      - jupyterlab=1.2.6
      - jupytext=1.14.4
      - matplotlib=3.6.2
      - mypy=0.910
      - numpy=1.24.1
      - numpydoc=1.5.0
      - pandas=1.5.2
      - pytest=7.2.0
      - pytest-cov=4.0.0
      - scikit-learn=1.1.3
      - scikit-optimize=0.9.0
      - sphinx=2.4.0
      - sphinx-gallery=0.10.1
      - sphinx_rtd_theme=1.0.0
      - statsmodels=0.11.0
      - twine=3.7.1
      - wheel=0.37.0
      - pip
      - pip:
              - plotly==5.11.0
              - pre-commit==2.21.0
              - -e .
