name: Unit tests

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  build-linux:
    if: github.event.pull_request.draft == false
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
      - name: Lock
        run: poetry lock --no-update
      - name: Install
        run: poetry install
      - name: Checkers
        run: make checkers
      - name: Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
