name: Unit tests fast

on:
  push:
    branches-ignore:
      - dev
      - main
  workflow_dispatch:

jobs:
  basic-testing:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # See caching environments
      # https://github.com/conda-incubator/setup-miniconda#caching-environments
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            use-mamba: true
            python-version: ${{ matrix.python-version }}

      - name: Get Date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Cache Poetry dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pypoetry/cache
            ~/.cache/pypoetry/artifacts
          key: poetry-${{ runner.os }}-cache-${{ steps.get-date.outputs.today }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-cache-

      - name: Install Poetry
        run :
          mamba install -c conda-forge poetry -y
          poetry install

      - name: Checkers
        run: make check-coverage check-types
