name: Unit tests

on:
  push:
    branches:
      -dev
      -main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  build-linux:
    if: github.event.pull_request.draft == false
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Git clone
        uses: actions/checkout@v3
      - name: Set up venv for ci
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{matrix.python-version}}
          environment-file: environment.ci.yml
      - name: Lint with flake8
        run: |
          flake8
      - name: Test with pytest
        run: |
          make coverage
      - name: typing with mypy
        run: |
          mypy qolmat
          echo you should uncomment mypy qolmat and delete this line
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
