name: Unit tests fast

on:
  push:
    branches-ignore:
      - dev
      - main
  workflow_dispatch:

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  basic-testing:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Git clone
        uses: actions/checkout@v3

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: env_qolmat_ci
            use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: ${{ matrix.prefix }}
          key: ${{ matrix.label }}-conda-${{ hashFiles('environment.ci.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run: mamba env update -n env_qolmat_ci -f environment.ci.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Lint with flake8
        run: |
          conda install flake8
          flake8
      - name: Test with pytest
        run: |
          conda install pytest
          pip install -e .[pytorch]
          make coverage
      - name: Test docstrings
        run: make doctest
      - name: typing with mypy
        run: |
          mypy qolmat
          echo you should uncomment mypy qolmat and delete this line
